import { ButtonLink, KeyValue, KeyValueGrid, Notice, Panel, PanelBody, PanelHeader, StatusChip } from "@/components/ui";
import { ScopeCard, TimelineEntry, WelfareHeader, WelfareMetric, WelfareSection } from "@/components/welfare/welfare-workspace";

export default async function WelfareCasePage({ params }: PageProps<"/[locale]/welfare/cases/[caseId]">) {
  const { caseId } = await params;
  return <>
    <WelfareHeader title={`Case ${caseId}`} subtitle="Nguyen Van An · DEMO-001 / STU-2024-001 · B.Sc. Computing & Software Systems, Year 3" actions={<><ButtonLink href="/welfare/cases/REF-001/intervention" size="sm" icon="history_edu">Record intervention</ButtonLink><ButtonLink href="/welfare/cases/REF-001/follow-up" variant="secondary" size="sm" icon="event_repeat">Support follow-up</ButtonLink></>} />
    <div className="flex flex-wrap items-center gap-space-sm"><StatusChip tone="referral" icon="pending" label="In triage / active casework" /><StatusChip tone="attention" icon="schedule" label="Priority P2 · 48h SLA" /><span className="font-code-audit text-code-audit text-on-surface-variant">Dispatched 07-Sep-2026 14:35 ICT</span></div>
    <div className="grid gap-space-lg xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.75fr)]">
      <div className="space-y-space-lg">
        <WelfareSection title="Referral & intake dossier" icon="assignment_turned_in" actions={<StatusChip tone="sealed" icon="lock" label="Committed record" />}>
          <div className="space-y-space-lg"><div className="border border-outline-variant/30 bg-surface-container-low px-space-md py-space-base"><p className="font-caption text-caption uppercase tracking-wider text-on-surface-variant">Primary welfare categorization</p><div className="mt-space-xs flex flex-wrap items-center gap-space-sm"><h2 className="font-headline-md text-headline-md">Housing & living stability friction</h2><span className="font-code-audit text-code-audit text-primary">ATTR-RES-004</span></div><p className="mt-space-sm font-body-sm text-body-sm text-on-surface-variant">Severe commute disruption is affecting core laboratory attendance and student physical wellbeing.</p></div><div><div className="flex flex-wrap justify-between gap-space-sm"><p className="font-label-md text-label-md font-semibold">Referring statement · Demo Advisor 01</p><span className="font-code-audit text-code-audit text-on-surface-variant">07-Sep-2026 14:35 ICT</span></div><blockquote className="mt-space-sm border-l-2 border-primary bg-surface-container-low px-space-md py-space-md font-body-sm text-body-sm italic">Urgent accommodation liaison and university residential welfare support requested following CS301 laboratory commute disruption. Student consent verified under the housing domain. Commute now exceeds 2.5 hours each way via three public bus transfers.</blockquote></div><div className="border border-outline-variant/30 px-space-md py-space-base"><div className="grid gap-space-md sm:grid-cols-3"><KeyValue label="Assigned caseworker" value="Demo Welfare Officer 01" /><KeyValue label="Triage outcome" value="Accepted for active casework" /><KeyValue label="Action trajectory" value="Emergency hall + voucher" /></div><p className="mt-space-md bg-surface-container-low px-space-md py-space-sm font-body-sm text-body-sm"><strong className="text-primary">Initial plan:</strong> Liaise with Student Housing for emergency placement and issue a transit hardship voucher during the transition window.</p></div></div>
        </WelfareSection>
        <WelfareSection title="Chronological activity & audit trail" icon="timeline" actions={<span className="font-code-audit text-code-audit text-on-surface-variant">APPEND-ONLY STREAM</span>}><div className="space-y-space-sm"><TimelineEntry icon="send" title="Referral accepted by Demo Welfare Officer 01" meta="07-Sep-2026 · 15:10 ICT">Caseworker triage completed within the 48-hour service target.</TimelineEntry><TimelineEntry icon="home_work" title="Student Housing liaison dispatched" meta="08-Sep-2026 · 09:00 ICT">Ticket DORM-2026-9041 opened for transitional hall placement.</TimelineEntry><TimelineEntry icon="event" title="7-day support review scheduled" meta="15-Sep-2026 · 10:30 ICT">Review milestone is awaiting contact confirmation.</TimelineEntry></div></WelfareSection>
      </div>
      <div className="space-y-space-lg"><Panel><PanelHeader icon="person" title="Student context" /><PanelBody><KeyValueGrid columns={1}><KeyValue label="Student" value="Nguyen Van An" /><KeyValue label="Institutional reference" value="DEMO-001 / STU-2024-001" mono /><KeyValue label="Referring advisor" value="Demo Advisor 01" /><KeyValue label="Consent token" value="CONS-082 · active" mono /></KeyValueGrid></PanelBody></Panel><Panel><PanelHeader icon="privacy_tip" title="Authorized data scope" subtitle="Only minimum-necessary attributes are visible" /><PanelBody className="space-y-space-md"><ScopeCard title="Housing-support need · ATTR-RES-004" body="Consent verified on 02-Sep-2026. Residence disruption and commute impact may be used for welfare coordination." /><ScopeCard title="Financial circumstances · ATTR-FIN-001" body="No active consent for this purpose. Financial details are quarantined and cannot be copied into casework." allowed={false} /><ScopeCard title="Academic diagnostics" body="Purpose boundary excludes detailed grades, attendance narratives, and examination records." allowed={false} /></PanelBody></Panel><Notice tone="referral" icon="rule" title="Casework boundary">All interventions and follow-ups append to this welfare case only. Corrections require an institutional addendum after commitment.</Notice><WelfareMetric label="Next milestone" value="15 Sep" detail="7-day support check-in · 10:30 ICT" icon="event" /></div>
    </div>
  </>;
}
